name: Build Docker

on:
  workflow_dispatch:
    inputs:
      alpine_tag:
        description: 'Tag of alpine docker image'
        required: true
        type: string
        default: '3.18.4'

      rsyslog_version:
        description: 'Version of rsyslog-tls package'
        required: true
        type: string
        default: '8.2306.0-r2'

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          context: git
          images: |
            cloudptsd/rsyslog-mezmo
          tags: |
            type=raw,value=latest
            type=raw,value=${{ inputs.rsyslog_version }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          push: true
          build-args: |
            ALPINE_TAG=${{ inputs.alpine_tag }}
            RSYSLOG_VERSION=${{ inputs.rsyslog_version }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

permissions:
  contents: write